/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTopPropsRouteImport } from './routes/_authenticated/top-props'
import { Route as AuthenticatedStandingsRouteImport } from './routes/_authenticated/standings'
import { Route as AuthenticatedSlateRouteImport } from './routes/_authenticated/slate'
import { Route as AuthenticatedSimLeadersRouteImport } from './routes/_authenticated/sim-leaders'
import { Route as AuthenticatedScoresRouteImport } from './routes/_authenticated/scores'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedProjectionsRouteImport } from './routes/_authenticated/projections'
import { Route as AuthenticatedOddsRouteImport } from './routes/_authenticated/odds'
import { Route as AuthenticatedModelResultsRouteImport } from './routes/_authenticated/model-results'
import { Route as AuthenticatedModelRouteImport } from './routes/_authenticated/model'
import { Route as AuthenticatedLineupStatusRouteImport } from './routes/_authenticated/lineup-status'
import { Route as AuthenticatedLeadersRouteImport } from './routes/_authenticated/leaders'
import { Route as AuthenticatedLeaderboardsRouteImport } from './routes/_authenticated/leaderboards'
import { Route as AuthenticatedForecastsRouteImport } from './routes/_authenticated/forecasts'
import { Route as AuthenticatedDiamondScoresRouteImport } from './routes/_authenticated/diamond-scores'
import { Route as AuthenticatedDiamondConsensusRouteImport } from './routes/_authenticated/diamond-consensus'
import { Route as AuthenticatedCalibrationLabRouteImport } from './routes/_authenticated/calibration-lab'
import { Route as AuthenticatedCalibrationRouteImport } from './routes/_authenticated/calibration'
import { Route as AuthenticatedBetsRouteImport } from './routes/_authenticated/bets'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedForecastsIndexRouteImport } from './routes/_authenticated/forecasts.index'
import { Route as AuthenticatedTodayLiveRouteImport } from './routes/_authenticated/today.live'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams.$teamId'
import { Route as AuthenticatedPlayersPlayerIdRouteImport } from './routes/_authenticated/players.$playerId'
import { Route as AuthenticatedMatchupsGamePkRouteImport } from './routes/_authenticated/matchups.$gamePk'
import { Route as AuthenticatedForecastsLabRouteImport } from './routes/_authenticated/forecasts.lab'
import { Route as AuthenticatedForecastsConsensusRouteImport } from './routes/_authenticated/forecasts.consensus'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedForecastsLabIndexRouteImport } from './routes/_authenticated/forecasts.lab.index'
import { Route as ApiPublicHooksRefreshLiveActualsRouteImport } from './routes/api/public/hooks/refresh-live-actuals'
import { Route as ApiPublicHooksRefreshLineupsRouteImport } from './routes/api/public/hooks/refresh-lineups'
import { Route as ApiPublicHooksOrchestrateSlateRouteImport } from './routes/api/public/hooks/orchestrate-slate'
import { Route as ApiPublicHooksLockLiveForecastsRouteImport } from './routes/api/public/hooks/lock-live-forecasts'
import { Route as ApiPublicHooksBeforeUserCreatedRouteImport } from './routes/api/public/hooks/before-user-created'
import { Route as AuthenticatedForecastsLabMeansRouteImport } from './routes/_authenticated/forecasts.lab.means'
import { Route as AuthenticatedForecastsLabAlphaRouteImport } from './routes/_authenticated/forecasts.lab.alpha'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopPropsRoute = AuthenticatedTopPropsRouteImport.update({
  id: '/top-props',
  path: '/top-props',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStandingsRoute = AuthenticatedStandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSlateRoute = AuthenticatedSlateRouteImport.update({
  id: '/slate',
  path: '/slate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimLeadersRoute = AuthenticatedSimLeadersRouteImport.update({
  id: '/sim-leaders',
  path: '/sim-leaders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScoresRoute = AuthenticatedScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectionsRoute =
  AuthenticatedProjectionsRouteImport.update({
    id: '/projections',
    path: '/projections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOddsRoute = AuthenticatedOddsRouteImport.update({
  id: '/odds',
  path: '/odds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelResultsRoute =
  AuthenticatedModelResultsRouteImport.update({
    id: '/model-results',
    path: '/model-results',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelRoute = AuthenticatedModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLineupStatusRoute =
  AuthenticatedLineupStatusRouteImport.update({
    id: '/lineup-status',
    path: '/lineup-status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadersRoute = AuthenticatedLeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardsRoute =
  AuthenticatedLeaderboardsRouteImport.update({
    id: '/leaderboards',
    path: '/leaderboards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedForecastsRoute = AuthenticatedForecastsRouteImport.update({
  id: '/forecasts',
  path: '/forecasts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiamondScoresRoute =
  AuthenticatedDiamondScoresRouteImport.update({
    id: '/diamond-scores',
    path: '/diamond-scores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiamondConsensusRoute =
  AuthenticatedDiamondConsensusRouteImport.update({
    id: '/diamond-consensus',
    path: '/diamond-consensus',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalibrationLabRoute =
  AuthenticatedCalibrationLabRouteImport.update({
    id: '/calibration-lab',
    path: '/calibration-lab',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalibrationRoute =
  AuthenticatedCalibrationRouteImport.update({
    id: '/calibration',
    path: '/calibration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBetsRoute = AuthenticatedBetsRouteImport.update({
  id: '/bets',
  path: '/bets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForecastsIndexRoute =
  AuthenticatedForecastsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedForecastsRoute,
  } as any)
const AuthenticatedTodayLiveRoute = AuthenticatedTodayLiveRouteImport.update({
  id: '/today/live',
  path: '/today/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayersPlayerIdRoute =
  AuthenticatedPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchupsGamePkRoute =
  AuthenticatedMatchupsGamePkRouteImport.update({
    id: '/matchups/$gamePk',
    path: '/matchups/$gamePk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedForecastsLabRoute =
  AuthenticatedForecastsLabRouteImport.update({
    id: '/lab',
    path: '/lab',
    getParentRoute: () => AuthenticatedForecastsRoute,
  } as any)
const AuthenticatedForecastsConsensusRoute =
  AuthenticatedForecastsConsensusRouteImport.update({
    id: '/consensus',
    path: '/consensus',
    getParentRoute: () => AuthenticatedForecastsRoute,
  } as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedForecastsLabIndexRoute =
  AuthenticatedForecastsLabIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedForecastsLabRoute,
  } as any)
const ApiPublicHooksRefreshLiveActualsRoute =
  ApiPublicHooksRefreshLiveActualsRouteImport.update({
    id: '/api/public/hooks/refresh-live-actuals',
    path: '/api/public/hooks/refresh-live-actuals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshLineupsRoute =
  ApiPublicHooksRefreshLineupsRouteImport.update({
    id: '/api/public/hooks/refresh-lineups',
    path: '/api/public/hooks/refresh-lineups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOrchestrateSlateRoute =
  ApiPublicHooksOrchestrateSlateRouteImport.update({
    id: '/api/public/hooks/orchestrate-slate',
    path: '/api/public/hooks/orchestrate-slate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLockLiveForecastsRoute =
  ApiPublicHooksLockLiveForecastsRouteImport.update({
    id: '/api/public/hooks/lock-live-forecasts',
    path: '/api/public/hooks/lock-live-forecasts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBeforeUserCreatedRoute =
  ApiPublicHooksBeforeUserCreatedRouteImport.update({
    id: '/api/public/hooks/before-user-created',
    path: '/api/public/hooks/before-user-created',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedForecastsLabMeansRoute =
  AuthenticatedForecastsLabMeansRouteImport.update({
    id: '/means',
    path: '/means',
    getParentRoute: () => AuthenticatedForecastsLabRoute,
  } as any)
const AuthenticatedForecastsLabAlphaRoute =
  AuthenticatedForecastsLabAlphaRouteImport.update({
    id: '/alpha',
    path: '/alpha',
    getParentRoute: () => AuthenticatedForecastsLabRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/bets': typeof AuthenticatedBetsRoute
  '/calibration': typeof AuthenticatedCalibrationRoute
  '/calibration-lab': typeof AuthenticatedCalibrationLabRoute
  '/diamond-consensus': typeof AuthenticatedDiamondConsensusRoute
  '/diamond-scores': typeof AuthenticatedDiamondScoresRoute
  '/forecasts': typeof AuthenticatedForecastsRouteWithChildren
  '/leaderboards': typeof AuthenticatedLeaderboardsRoute
  '/leaders': typeof AuthenticatedLeadersRoute
  '/lineup-status': typeof AuthenticatedLineupStatusRoute
  '/model': typeof AuthenticatedModelRoute
  '/model-results': typeof AuthenticatedModelResultsRoute
  '/odds': typeof AuthenticatedOddsRoute
  '/projections': typeof AuthenticatedProjectionsRoute
  '/results': typeof AuthenticatedResultsRoute
  '/scores': typeof AuthenticatedScoresRoute
  '/sim-leaders': typeof AuthenticatedSimLeadersRoute
  '/slate': typeof AuthenticatedSlateRoute
  '/standings': typeof AuthenticatedStandingsRoute
  '/top-props': typeof AuthenticatedTopPropsRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/forecasts/consensus': typeof AuthenticatedForecastsConsensusRoute
  '/forecasts/lab': typeof AuthenticatedForecastsLabRouteWithChildren
  '/matchups/$gamePk': typeof AuthenticatedMatchupsGamePkRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/today/live': typeof AuthenticatedTodayLiveRoute
  '/forecasts/': typeof AuthenticatedForecastsIndexRoute
  '/forecasts/lab/alpha': typeof AuthenticatedForecastsLabAlphaRoute
  '/forecasts/lab/means': typeof AuthenticatedForecastsLabMeansRoute
  '/api/public/hooks/before-user-created': typeof ApiPublicHooksBeforeUserCreatedRoute
  '/api/public/hooks/lock-live-forecasts': typeof ApiPublicHooksLockLiveForecastsRoute
  '/api/public/hooks/orchestrate-slate': typeof ApiPublicHooksOrchestrateSlateRoute
  '/api/public/hooks/refresh-lineups': typeof ApiPublicHooksRefreshLineupsRoute
  '/api/public/hooks/refresh-live-actuals': typeof ApiPublicHooksRefreshLiveActualsRoute
  '/forecasts/lab/': typeof AuthenticatedForecastsLabIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/bets': typeof AuthenticatedBetsRoute
  '/calibration': typeof AuthenticatedCalibrationRoute
  '/calibration-lab': typeof AuthenticatedCalibrationLabRoute
  '/diamond-consensus': typeof AuthenticatedDiamondConsensusRoute
  '/diamond-scores': typeof AuthenticatedDiamondScoresRoute
  '/leaderboards': typeof AuthenticatedLeaderboardsRoute
  '/leaders': typeof AuthenticatedLeadersRoute
  '/lineup-status': typeof AuthenticatedLineupStatusRoute
  '/model': typeof AuthenticatedModelRoute
  '/model-results': typeof AuthenticatedModelResultsRoute
  '/odds': typeof AuthenticatedOddsRoute
  '/projections': typeof AuthenticatedProjectionsRoute
  '/results': typeof AuthenticatedResultsRoute
  '/scores': typeof AuthenticatedScoresRoute
  '/sim-leaders': typeof AuthenticatedSimLeadersRoute
  '/slate': typeof AuthenticatedSlateRoute
  '/standings': typeof AuthenticatedStandingsRoute
  '/top-props': typeof AuthenticatedTopPropsRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/forecasts/consensus': typeof AuthenticatedForecastsConsensusRoute
  '/matchups/$gamePk': typeof AuthenticatedMatchupsGamePkRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/today/live': typeof AuthenticatedTodayLiveRoute
  '/forecasts': typeof AuthenticatedForecastsIndexRoute
  '/forecasts/lab/alpha': typeof AuthenticatedForecastsLabAlphaRoute
  '/forecasts/lab/means': typeof AuthenticatedForecastsLabMeansRoute
  '/api/public/hooks/before-user-created': typeof ApiPublicHooksBeforeUserCreatedRoute
  '/api/public/hooks/lock-live-forecasts': typeof ApiPublicHooksLockLiveForecastsRoute
  '/api/public/hooks/orchestrate-slate': typeof ApiPublicHooksOrchestrateSlateRoute
  '/api/public/hooks/refresh-lineups': typeof ApiPublicHooksRefreshLineupsRoute
  '/api/public/hooks/refresh-live-actuals': typeof ApiPublicHooksRefreshLiveActualsRoute
  '/forecasts/lab': typeof AuthenticatedForecastsLabIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/bets': typeof AuthenticatedBetsRoute
  '/_authenticated/calibration': typeof AuthenticatedCalibrationRoute
  '/_authenticated/calibration-lab': typeof AuthenticatedCalibrationLabRoute
  '/_authenticated/diamond-consensus': typeof AuthenticatedDiamondConsensusRoute
  '/_authenticated/diamond-scores': typeof AuthenticatedDiamondScoresRoute
  '/_authenticated/forecasts': typeof AuthenticatedForecastsRouteWithChildren
  '/_authenticated/leaderboards': typeof AuthenticatedLeaderboardsRoute
  '/_authenticated/leaders': typeof AuthenticatedLeadersRoute
  '/_authenticated/lineup-status': typeof AuthenticatedLineupStatusRoute
  '/_authenticated/model': typeof AuthenticatedModelRoute
  '/_authenticated/model-results': typeof AuthenticatedModelResultsRoute
  '/_authenticated/odds': typeof AuthenticatedOddsRoute
  '/_authenticated/projections': typeof AuthenticatedProjectionsRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/scores': typeof AuthenticatedScoresRoute
  '/_authenticated/sim-leaders': typeof AuthenticatedSimLeadersRoute
  '/_authenticated/slate': typeof AuthenticatedSlateRoute
  '/_authenticated/standings': typeof AuthenticatedStandingsRoute
  '/_authenticated/top-props': typeof AuthenticatedTopPropsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRoute
  '/_authenticated/forecasts/consensus': typeof AuthenticatedForecastsConsensusRoute
  '/_authenticated/forecasts/lab': typeof AuthenticatedForecastsLabRouteWithChildren
  '/_authenticated/matchups/$gamePk': typeof AuthenticatedMatchupsGamePkRoute
  '/_authenticated/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/_authenticated/today/live': typeof AuthenticatedTodayLiveRoute
  '/_authenticated/forecasts/': typeof AuthenticatedForecastsIndexRoute
  '/_authenticated/forecasts/lab/alpha': typeof AuthenticatedForecastsLabAlphaRoute
  '/_authenticated/forecasts/lab/means': typeof AuthenticatedForecastsLabMeansRoute
  '/api/public/hooks/before-user-created': typeof ApiPublicHooksBeforeUserCreatedRoute
  '/api/public/hooks/lock-live-forecasts': typeof ApiPublicHooksLockLiveForecastsRoute
  '/api/public/hooks/orchestrate-slate': typeof ApiPublicHooksOrchestrateSlateRoute
  '/api/public/hooks/refresh-lineups': typeof ApiPublicHooksRefreshLineupsRoute
  '/api/public/hooks/refresh-live-actuals': typeof ApiPublicHooksRefreshLiveActualsRoute
  '/_authenticated/forecasts/lab/': typeof AuthenticatedForecastsLabIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bets'
    | '/calibration'
    | '/calibration-lab'
    | '/diamond-consensus'
    | '/diamond-scores'
    | '/forecasts'
    | '/leaderboards'
    | '/leaders'
    | '/lineup-status'
    | '/model'
    | '/model-results'
    | '/odds'
    | '/projections'
    | '/results'
    | '/scores'
    | '/sim-leaders'
    | '/slate'
    | '/standings'
    | '/top-props'
    | '/admin'
    | '/forecasts/consensus'
    | '/forecasts/lab'
    | '/matchups/$gamePk'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/today/live'
    | '/forecasts/'
    | '/forecasts/lab/alpha'
    | '/forecasts/lab/means'
    | '/api/public/hooks/before-user-created'
    | '/api/public/hooks/lock-live-forecasts'
    | '/api/public/hooks/orchestrate-slate'
    | '/api/public/hooks/refresh-lineups'
    | '/api/public/hooks/refresh-live-actuals'
    | '/forecasts/lab/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/bets'
    | '/calibration'
    | '/calibration-lab'
    | '/diamond-consensus'
    | '/diamond-scores'
    | '/leaderboards'
    | '/leaders'
    | '/lineup-status'
    | '/model'
    | '/model-results'
    | '/odds'
    | '/projections'
    | '/results'
    | '/scores'
    | '/sim-leaders'
    | '/slate'
    | '/standings'
    | '/top-props'
    | '/admin'
    | '/forecasts/consensus'
    | '/matchups/$gamePk'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/today/live'
    | '/forecasts'
    | '/forecasts/lab/alpha'
    | '/forecasts/lab/means'
    | '/api/public/hooks/before-user-created'
    | '/api/public/hooks/lock-live-forecasts'
    | '/api/public/hooks/orchestrate-slate'
    | '/api/public/hooks/refresh-lineups'
    | '/api/public/hooks/refresh-live-actuals'
    | '/forecasts/lab'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_admin'
    | '/_authenticated/bets'
    | '/_authenticated/calibration'
    | '/_authenticated/calibration-lab'
    | '/_authenticated/diamond-consensus'
    | '/_authenticated/diamond-scores'
    | '/_authenticated/forecasts'
    | '/_authenticated/leaderboards'
    | '/_authenticated/leaders'
    | '/_authenticated/lineup-status'
    | '/_authenticated/model'
    | '/_authenticated/model-results'
    | '/_authenticated/odds'
    | '/_authenticated/projections'
    | '/_authenticated/results'
    | '/_authenticated/scores'
    | '/_authenticated/sim-leaders'
    | '/_authenticated/slate'
    | '/_authenticated/standings'
    | '/_authenticated/top-props'
    | '/_authenticated/'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/forecasts/consensus'
    | '/_authenticated/forecasts/lab'
    | '/_authenticated/matchups/$gamePk'
    | '/_authenticated/players/$playerId'
    | '/_authenticated/teams/$teamId'
    | '/_authenticated/today/live'
    | '/_authenticated/forecasts/'
    | '/_authenticated/forecasts/lab/alpha'
    | '/_authenticated/forecasts/lab/means'
    | '/api/public/hooks/before-user-created'
    | '/api/public/hooks/lock-live-forecasts'
    | '/api/public/hooks/orchestrate-slate'
    | '/api/public/hooks/refresh-lineups'
    | '/api/public/hooks/refresh-live-actuals'
    | '/_authenticated/forecasts/lab/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksBeforeUserCreatedRoute: typeof ApiPublicHooksBeforeUserCreatedRoute
  ApiPublicHooksLockLiveForecastsRoute: typeof ApiPublicHooksLockLiveForecastsRoute
  ApiPublicHooksOrchestrateSlateRoute: typeof ApiPublicHooksOrchestrateSlateRoute
  ApiPublicHooksRefreshLineupsRoute: typeof ApiPublicHooksRefreshLineupsRoute
  ApiPublicHooksRefreshLiveActualsRoute: typeof ApiPublicHooksRefreshLiveActualsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/top-props': {
      id: '/_authenticated/top-props'
      path: '/top-props'
      fullPath: '/top-props'
      preLoaderRoute: typeof AuthenticatedTopPropsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/standings': {
      id: '/_authenticated/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof AuthenticatedStandingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/slate': {
      id: '/_authenticated/slate'
      path: '/slate'
      fullPath: '/slate'
      preLoaderRoute: typeof AuthenticatedSlateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sim-leaders': {
      id: '/_authenticated/sim-leaders'
      path: '/sim-leaders'
      fullPath: '/sim-leaders'
      preLoaderRoute: typeof AuthenticatedSimLeadersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scores': {
      id: '/_authenticated/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof AuthenticatedScoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projections': {
      id: '/_authenticated/projections'
      path: '/projections'
      fullPath: '/projections'
      preLoaderRoute: typeof AuthenticatedProjectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/odds': {
      id: '/_authenticated/odds'
      path: '/odds'
      fullPath: '/odds'
      preLoaderRoute: typeof AuthenticatedOddsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/model-results': {
      id: '/_authenticated/model-results'
      path: '/model-results'
      fullPath: '/model-results'
      preLoaderRoute: typeof AuthenticatedModelResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/model': {
      id: '/_authenticated/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof AuthenticatedModelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lineup-status': {
      id: '/_authenticated/lineup-status'
      path: '/lineup-status'
      fullPath: '/lineup-status'
      preLoaderRoute: typeof AuthenticatedLineupStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaders': {
      id: '/_authenticated/leaders'
      path: '/leaders'
      fullPath: '/leaders'
      preLoaderRoute: typeof AuthenticatedLeadersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboards': {
      id: '/_authenticated/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof AuthenticatedLeaderboardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forecasts': {
      id: '/_authenticated/forecasts'
      path: '/forecasts'
      fullPath: '/forecasts'
      preLoaderRoute: typeof AuthenticatedForecastsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diamond-scores': {
      id: '/_authenticated/diamond-scores'
      path: '/diamond-scores'
      fullPath: '/diamond-scores'
      preLoaderRoute: typeof AuthenticatedDiamondScoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diamond-consensus': {
      id: '/_authenticated/diamond-consensus'
      path: '/diamond-consensus'
      fullPath: '/diamond-consensus'
      preLoaderRoute: typeof AuthenticatedDiamondConsensusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calibration-lab': {
      id: '/_authenticated/calibration-lab'
      path: '/calibration-lab'
      fullPath: '/calibration-lab'
      preLoaderRoute: typeof AuthenticatedCalibrationLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calibration': {
      id: '/_authenticated/calibration'
      path: '/calibration'
      fullPath: '/calibration'
      preLoaderRoute: typeof AuthenticatedCalibrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bets': {
      id: '/_authenticated/bets'
      path: '/bets'
      fullPath: '/bets'
      preLoaderRoute: typeof AuthenticatedBetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forecasts/': {
      id: '/_authenticated/forecasts/'
      path: '/'
      fullPath: '/forecasts/'
      preLoaderRoute: typeof AuthenticatedForecastsIndexRouteImport
      parentRoute: typeof AuthenticatedForecastsRoute
    }
    '/_authenticated/today/live': {
      id: '/_authenticated/today/live'
      path: '/today/live'
      fullPath: '/today/live'
      preLoaderRoute: typeof AuthenticatedTodayLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players/$playerId': {
      id: '/_authenticated/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof AuthenticatedPlayersPlayerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matchups/$gamePk': {
      id: '/_authenticated/matchups/$gamePk'
      path: '/matchups/$gamePk'
      fullPath: '/matchups/$gamePk'
      preLoaderRoute: typeof AuthenticatedMatchupsGamePkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forecasts/lab': {
      id: '/_authenticated/forecasts/lab'
      path: '/lab'
      fullPath: '/forecasts/lab'
      preLoaderRoute: typeof AuthenticatedForecastsLabRouteImport
      parentRoute: typeof AuthenticatedForecastsRoute
    }
    '/_authenticated/forecasts/consensus': {
      id: '/_authenticated/forecasts/consensus'
      path: '/consensus'
      fullPath: '/forecasts/consensus'
      preLoaderRoute: typeof AuthenticatedForecastsConsensusRouteImport
      parentRoute: typeof AuthenticatedForecastsRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/forecasts/lab/': {
      id: '/_authenticated/forecasts/lab/'
      path: '/'
      fullPath: '/forecasts/lab/'
      preLoaderRoute: typeof AuthenticatedForecastsLabIndexRouteImport
      parentRoute: typeof AuthenticatedForecastsLabRoute
    }
    '/api/public/hooks/refresh-live-actuals': {
      id: '/api/public/hooks/refresh-live-actuals'
      path: '/api/public/hooks/refresh-live-actuals'
      fullPath: '/api/public/hooks/refresh-live-actuals'
      preLoaderRoute: typeof ApiPublicHooksRefreshLiveActualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-lineups': {
      id: '/api/public/hooks/refresh-lineups'
      path: '/api/public/hooks/refresh-lineups'
      fullPath: '/api/public/hooks/refresh-lineups'
      preLoaderRoute: typeof ApiPublicHooksRefreshLineupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/orchestrate-slate': {
      id: '/api/public/hooks/orchestrate-slate'
      path: '/api/public/hooks/orchestrate-slate'
      fullPath: '/api/public/hooks/orchestrate-slate'
      preLoaderRoute: typeof ApiPublicHooksOrchestrateSlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lock-live-forecasts': {
      id: '/api/public/hooks/lock-live-forecasts'
      path: '/api/public/hooks/lock-live-forecasts'
      fullPath: '/api/public/hooks/lock-live-forecasts'
      preLoaderRoute: typeof ApiPublicHooksLockLiveForecastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/before-user-created': {
      id: '/api/public/hooks/before-user-created'
      path: '/api/public/hooks/before-user-created'
      fullPath: '/api/public/hooks/before-user-created'
      preLoaderRoute: typeof ApiPublicHooksBeforeUserCreatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/forecasts/lab/means': {
      id: '/_authenticated/forecasts/lab/means'
      path: '/means'
      fullPath: '/forecasts/lab/means'
      preLoaderRoute: typeof AuthenticatedForecastsLabMeansRouteImport
      parentRoute: typeof AuthenticatedForecastsLabRoute
    }
    '/_authenticated/forecasts/lab/alpha': {
      id: '/_authenticated/forecasts/lab/alpha'
      path: '/alpha'
      fullPath: '/forecasts/lab/alpha'
      preLoaderRoute: typeof AuthenticatedForecastsLabAlphaRouteImport
      parentRoute: typeof AuthenticatedForecastsLabRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedForecastsLabRouteChildren {
  AuthenticatedForecastsLabAlphaRoute: typeof AuthenticatedForecastsLabAlphaRoute
  AuthenticatedForecastsLabMeansRoute: typeof AuthenticatedForecastsLabMeansRoute
  AuthenticatedForecastsLabIndexRoute: typeof AuthenticatedForecastsLabIndexRoute
}

const AuthenticatedForecastsLabRouteChildren: AuthenticatedForecastsLabRouteChildren =
  {
    AuthenticatedForecastsLabAlphaRoute: AuthenticatedForecastsLabAlphaRoute,
    AuthenticatedForecastsLabMeansRoute: AuthenticatedForecastsLabMeansRoute,
    AuthenticatedForecastsLabIndexRoute: AuthenticatedForecastsLabIndexRoute,
  }

const AuthenticatedForecastsLabRouteWithChildren =
  AuthenticatedForecastsLabRoute._addFileChildren(
    AuthenticatedForecastsLabRouteChildren,
  )

interface AuthenticatedForecastsRouteChildren {
  AuthenticatedForecastsConsensusRoute: typeof AuthenticatedForecastsConsensusRoute
  AuthenticatedForecastsLabRoute: typeof AuthenticatedForecastsLabRouteWithChildren
  AuthenticatedForecastsIndexRoute: typeof AuthenticatedForecastsIndexRoute
}

const AuthenticatedForecastsRouteChildren: AuthenticatedForecastsRouteChildren =
  {
    AuthenticatedForecastsConsensusRoute: AuthenticatedForecastsConsensusRoute,
    AuthenticatedForecastsLabRoute: AuthenticatedForecastsLabRouteWithChildren,
    AuthenticatedForecastsIndexRoute: AuthenticatedForecastsIndexRoute,
  }

const AuthenticatedForecastsRouteWithChildren =
  AuthenticatedForecastsRoute._addFileChildren(
    AuthenticatedForecastsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedBetsRoute: typeof AuthenticatedBetsRoute
  AuthenticatedCalibrationRoute: typeof AuthenticatedCalibrationRoute
  AuthenticatedCalibrationLabRoute: typeof AuthenticatedCalibrationLabRoute
  AuthenticatedDiamondConsensusRoute: typeof AuthenticatedDiamondConsensusRoute
  AuthenticatedDiamondScoresRoute: typeof AuthenticatedDiamondScoresRoute
  AuthenticatedForecastsRoute: typeof AuthenticatedForecastsRouteWithChildren
  AuthenticatedLeaderboardsRoute: typeof AuthenticatedLeaderboardsRoute
  AuthenticatedLeadersRoute: typeof AuthenticatedLeadersRoute
  AuthenticatedLineupStatusRoute: typeof AuthenticatedLineupStatusRoute
  AuthenticatedModelRoute: typeof AuthenticatedModelRoute
  AuthenticatedModelResultsRoute: typeof AuthenticatedModelResultsRoute
  AuthenticatedOddsRoute: typeof AuthenticatedOddsRoute
  AuthenticatedProjectionsRoute: typeof AuthenticatedProjectionsRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedScoresRoute: typeof AuthenticatedScoresRoute
  AuthenticatedSimLeadersRoute: typeof AuthenticatedSimLeadersRoute
  AuthenticatedSlateRoute: typeof AuthenticatedSlateRoute
  AuthenticatedStandingsRoute: typeof AuthenticatedStandingsRoute
  AuthenticatedTopPropsRoute: typeof AuthenticatedTopPropsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMatchupsGamePkRoute: typeof AuthenticatedMatchupsGamePkRoute
  AuthenticatedPlayersPlayerIdRoute: typeof AuthenticatedPlayersPlayerIdRoute
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRoute
  AuthenticatedTodayLiveRoute: typeof AuthenticatedTodayLiveRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedBetsRoute: AuthenticatedBetsRoute,
  AuthenticatedCalibrationRoute: AuthenticatedCalibrationRoute,
  AuthenticatedCalibrationLabRoute: AuthenticatedCalibrationLabRoute,
  AuthenticatedDiamondConsensusRoute: AuthenticatedDiamondConsensusRoute,
  AuthenticatedDiamondScoresRoute: AuthenticatedDiamondScoresRoute,
  AuthenticatedForecastsRoute: AuthenticatedForecastsRouteWithChildren,
  AuthenticatedLeaderboardsRoute: AuthenticatedLeaderboardsRoute,
  AuthenticatedLeadersRoute: AuthenticatedLeadersRoute,
  AuthenticatedLineupStatusRoute: AuthenticatedLineupStatusRoute,
  AuthenticatedModelRoute: AuthenticatedModelRoute,
  AuthenticatedModelResultsRoute: AuthenticatedModelResultsRoute,
  AuthenticatedOddsRoute: AuthenticatedOddsRoute,
  AuthenticatedProjectionsRoute: AuthenticatedProjectionsRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedScoresRoute: AuthenticatedScoresRoute,
  AuthenticatedSimLeadersRoute: AuthenticatedSimLeadersRoute,
  AuthenticatedSlateRoute: AuthenticatedSlateRoute,
  AuthenticatedStandingsRoute: AuthenticatedStandingsRoute,
  AuthenticatedTopPropsRoute: AuthenticatedTopPropsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMatchupsGamePkRoute: AuthenticatedMatchupsGamePkRoute,
  AuthenticatedPlayersPlayerIdRoute: AuthenticatedPlayersPlayerIdRoute,
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRoute,
  AuthenticatedTodayLiveRoute: AuthenticatedTodayLiveRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksBeforeUserCreatedRoute: ApiPublicHooksBeforeUserCreatedRoute,
  ApiPublicHooksLockLiveForecastsRoute: ApiPublicHooksLockLiveForecastsRoute,
  ApiPublicHooksOrchestrateSlateRoute: ApiPublicHooksOrchestrateSlateRoute,
  ApiPublicHooksRefreshLineupsRoute: ApiPublicHooksRefreshLineupsRoute,
  ApiPublicHooksRefreshLiveActualsRoute: ApiPublicHooksRefreshLiveActualsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
