/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTopPropsRouteImport } from './routes/_authenticated/top-props'
import { Route as AuthenticatedStandingsRouteImport } from './routes/_authenticated/standings'
import { Route as AuthenticatedSlateRouteImport } from './routes/_authenticated/slate'
import { Route as AuthenticatedScoresRouteImport } from './routes/_authenticated/scores'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedOddsRouteImport } from './routes/_authenticated/odds'
import { Route as AuthenticatedLineupStatusRouteImport } from './routes/_authenticated/lineup-status'
import { Route as AuthenticatedLeaderboardsRouteImport } from './routes/_authenticated/leaderboards'
import { Route as AuthenticatedDiamondScoresRouteImport } from './routes/_authenticated/diamond-scores'
import { Route as AuthenticatedDiamondConsensusRouteImport } from './routes/_authenticated/diamond-consensus'
import { Route as AuthenticatedCalibrationLabRouteImport } from './routes/_authenticated/calibration-lab'
import { Route as AuthenticatedCalibrationRouteImport } from './routes/_authenticated/calibration'
import { Route as AuthenticatedBetsRouteImport } from './routes/_authenticated/bets'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams.$teamId'
import { Route as AuthenticatedPlayersPlayerIdRouteImport } from './routes/_authenticated/players.$playerId'
import { Route as AuthenticatedMatchupsGamePkRouteImport } from './routes/_authenticated/matchups.$gamePk'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as ApiPublicHooksRefreshLineupsRouteImport } from './routes/api/public/hooks/refresh-lineups'
import { Route as ApiPublicHooksBeforeUserCreatedRouteImport } from './routes/api/public/hooks/before-user-created'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopPropsRoute = AuthenticatedTopPropsRouteImport.update({
  id: '/top-props',
  path: '/top-props',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStandingsRoute = AuthenticatedStandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSlateRoute = AuthenticatedSlateRouteImport.update({
  id: '/slate',
  path: '/slate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScoresRoute = AuthenticatedScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOddsRoute = AuthenticatedOddsRouteImport.update({
  id: '/odds',
  path: '/odds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLineupStatusRoute =
  AuthenticatedLineupStatusRouteImport.update({
    id: '/lineup-status',
    path: '/lineup-status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaderboardsRoute =
  AuthenticatedLeaderboardsRouteImport.update({
    id: '/leaderboards',
    path: '/leaderboards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiamondScoresRoute =
  AuthenticatedDiamondScoresRouteImport.update({
    id: '/diamond-scores',
    path: '/diamond-scores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiamondConsensusRoute =
  AuthenticatedDiamondConsensusRouteImport.update({
    id: '/diamond-consensus',
    path: '/diamond-consensus',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalibrationLabRoute =
  AuthenticatedCalibrationLabRouteImport.update({
    id: '/calibration-lab',
    path: '/calibration-lab',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalibrationRoute =
  AuthenticatedCalibrationRouteImport.update({
    id: '/calibration',
    path: '/calibration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBetsRoute = AuthenticatedBetsRouteImport.update({
  id: '/bets',
  path: '/bets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayersPlayerIdRoute =
  AuthenticatedPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchupsGamePkRoute =
  AuthenticatedMatchupsGamePkRouteImport.update({
    id: '/matchups/$gamePk',
    path: '/matchups/$gamePk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicHooksRefreshLineupsRoute =
  ApiPublicHooksRefreshLineupsRouteImport.update({
    id: '/api/public/hooks/refresh-lineups',
    path: '/api/public/hooks/refresh-lineups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBeforeUserCreatedRoute =
  ApiPublicHooksBeforeUserCreatedRouteImport.update({
    id: '/api/public/hooks/before-user-created',
    path: '/api/public/hooks/before-user-created',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/bets': typeof AuthenticatedBetsRoute
  '/calibration': typeof AuthenticatedCalibrationRoute
  '/calibration-lab': typeof AuthenticatedCalibrationLabRoute
  '/diamond-consensus': typeof AuthenticatedDiamondConsensusRoute
  '/diamond-scores': typeof AuthenticatedDiamondScoresRoute
  '/leaderboards': typeof AuthenticatedLeaderboardsRoute
  '/lineup-status': typeof AuthenticatedLineupStatusRoute
  '/odds': typeof AuthenticatedOddsRoute
  '/results': typeof AuthenticatedResultsRoute
  '/scores': typeof AuthenticatedScoresRoute
  '/slate': typeof AuthenticatedSlateRoute
  '/standings': typeof AuthenticatedStandingsRoute
  '/top-props': typeof AuthenticatedTopPropsRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/matchups/$gamePk': typeof AuthenticatedMatchupsGamePkRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/api/public/hooks/before-user-created': typeof ApiPublicHooksBeforeUserCreatedRoute
  '/api/public/hooks/refresh-lineups': typeof ApiPublicHooksRefreshLineupsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/bets': typeof AuthenticatedBetsRoute
  '/calibration': typeof AuthenticatedCalibrationRoute
  '/calibration-lab': typeof AuthenticatedCalibrationLabRoute
  '/diamond-consensus': typeof AuthenticatedDiamondConsensusRoute
  '/diamond-scores': typeof AuthenticatedDiamondScoresRoute
  '/leaderboards': typeof AuthenticatedLeaderboardsRoute
  '/lineup-status': typeof AuthenticatedLineupStatusRoute
  '/odds': typeof AuthenticatedOddsRoute
  '/results': typeof AuthenticatedResultsRoute
  '/scores': typeof AuthenticatedScoresRoute
  '/slate': typeof AuthenticatedSlateRoute
  '/standings': typeof AuthenticatedStandingsRoute
  '/top-props': typeof AuthenticatedTopPropsRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/matchups/$gamePk': typeof AuthenticatedMatchupsGamePkRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/api/public/hooks/before-user-created': typeof ApiPublicHooksBeforeUserCreatedRoute
  '/api/public/hooks/refresh-lineups': typeof ApiPublicHooksRefreshLineupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/bets': typeof AuthenticatedBetsRoute
  '/_authenticated/calibration': typeof AuthenticatedCalibrationRoute
  '/_authenticated/calibration-lab': typeof AuthenticatedCalibrationLabRoute
  '/_authenticated/diamond-consensus': typeof AuthenticatedDiamondConsensusRoute
  '/_authenticated/diamond-scores': typeof AuthenticatedDiamondScoresRoute
  '/_authenticated/leaderboards': typeof AuthenticatedLeaderboardsRoute
  '/_authenticated/lineup-status': typeof AuthenticatedLineupStatusRoute
  '/_authenticated/odds': typeof AuthenticatedOddsRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/scores': typeof AuthenticatedScoresRoute
  '/_authenticated/slate': typeof AuthenticatedSlateRoute
  '/_authenticated/standings': typeof AuthenticatedStandingsRoute
  '/_authenticated/top-props': typeof AuthenticatedTopPropsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRoute
  '/_authenticated/matchups/$gamePk': typeof AuthenticatedMatchupsGamePkRoute
  '/_authenticated/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/api/public/hooks/before-user-created': typeof ApiPublicHooksBeforeUserCreatedRoute
  '/api/public/hooks/refresh-lineups': typeof ApiPublicHooksRefreshLineupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bets'
    | '/calibration'
    | '/calibration-lab'
    | '/diamond-consensus'
    | '/diamond-scores'
    | '/leaderboards'
    | '/lineup-status'
    | '/odds'
    | '/results'
    | '/scores'
    | '/slate'
    | '/standings'
    | '/top-props'
    | '/admin'
    | '/matchups/$gamePk'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/api/public/hooks/before-user-created'
    | '/api/public/hooks/refresh-lineups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/bets'
    | '/calibration'
    | '/calibration-lab'
    | '/diamond-consensus'
    | '/diamond-scores'
    | '/leaderboards'
    | '/lineup-status'
    | '/odds'
    | '/results'
    | '/scores'
    | '/slate'
    | '/standings'
    | '/top-props'
    | '/admin'
    | '/matchups/$gamePk'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/api/public/hooks/before-user-created'
    | '/api/public/hooks/refresh-lineups'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_admin'
    | '/_authenticated/bets'
    | '/_authenticated/calibration'
    | '/_authenticated/calibration-lab'
    | '/_authenticated/diamond-consensus'
    | '/_authenticated/diamond-scores'
    | '/_authenticated/leaderboards'
    | '/_authenticated/lineup-status'
    | '/_authenticated/odds'
    | '/_authenticated/results'
    | '/_authenticated/scores'
    | '/_authenticated/slate'
    | '/_authenticated/standings'
    | '/_authenticated/top-props'
    | '/_authenticated/'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/matchups/$gamePk'
    | '/_authenticated/players/$playerId'
    | '/_authenticated/teams/$teamId'
    | '/api/public/hooks/before-user-created'
    | '/api/public/hooks/refresh-lineups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksBeforeUserCreatedRoute: typeof ApiPublicHooksBeforeUserCreatedRoute
  ApiPublicHooksRefreshLineupsRoute: typeof ApiPublicHooksRefreshLineupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/top-props': {
      id: '/_authenticated/top-props'
      path: '/top-props'
      fullPath: '/top-props'
      preLoaderRoute: typeof AuthenticatedTopPropsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/standings': {
      id: '/_authenticated/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof AuthenticatedStandingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/slate': {
      id: '/_authenticated/slate'
      path: '/slate'
      fullPath: '/slate'
      preLoaderRoute: typeof AuthenticatedSlateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scores': {
      id: '/_authenticated/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof AuthenticatedScoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/odds': {
      id: '/_authenticated/odds'
      path: '/odds'
      fullPath: '/odds'
      preLoaderRoute: typeof AuthenticatedOddsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lineup-status': {
      id: '/_authenticated/lineup-status'
      path: '/lineup-status'
      fullPath: '/lineup-status'
      preLoaderRoute: typeof AuthenticatedLineupStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboards': {
      id: '/_authenticated/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof AuthenticatedLeaderboardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diamond-scores': {
      id: '/_authenticated/diamond-scores'
      path: '/diamond-scores'
      fullPath: '/diamond-scores'
      preLoaderRoute: typeof AuthenticatedDiamondScoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diamond-consensus': {
      id: '/_authenticated/diamond-consensus'
      path: '/diamond-consensus'
      fullPath: '/diamond-consensus'
      preLoaderRoute: typeof AuthenticatedDiamondConsensusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calibration-lab': {
      id: '/_authenticated/calibration-lab'
      path: '/calibration-lab'
      fullPath: '/calibration-lab'
      preLoaderRoute: typeof AuthenticatedCalibrationLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calibration': {
      id: '/_authenticated/calibration'
      path: '/calibration'
      fullPath: '/calibration'
      preLoaderRoute: typeof AuthenticatedCalibrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bets': {
      id: '/_authenticated/bets'
      path: '/bets'
      fullPath: '/bets'
      preLoaderRoute: typeof AuthenticatedBetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players/$playerId': {
      id: '/_authenticated/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof AuthenticatedPlayersPlayerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matchups/$gamePk': {
      id: '/_authenticated/matchups/$gamePk'
      path: '/matchups/$gamePk'
      fullPath: '/matchups/$gamePk'
      preLoaderRoute: typeof AuthenticatedMatchupsGamePkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/hooks/refresh-lineups': {
      id: '/api/public/hooks/refresh-lineups'
      path: '/api/public/hooks/refresh-lineups'
      fullPath: '/api/public/hooks/refresh-lineups'
      preLoaderRoute: typeof ApiPublicHooksRefreshLineupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/before-user-created': {
      id: '/api/public/hooks/before-user-created'
      path: '/api/public/hooks/before-user-created'
      fullPath: '/api/public/hooks/before-user-created'
      preLoaderRoute: typeof ApiPublicHooksBeforeUserCreatedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedBetsRoute: typeof AuthenticatedBetsRoute
  AuthenticatedCalibrationRoute: typeof AuthenticatedCalibrationRoute
  AuthenticatedCalibrationLabRoute: typeof AuthenticatedCalibrationLabRoute
  AuthenticatedDiamondConsensusRoute: typeof AuthenticatedDiamondConsensusRoute
  AuthenticatedDiamondScoresRoute: typeof AuthenticatedDiamondScoresRoute
  AuthenticatedLeaderboardsRoute: typeof AuthenticatedLeaderboardsRoute
  AuthenticatedLineupStatusRoute: typeof AuthenticatedLineupStatusRoute
  AuthenticatedOddsRoute: typeof AuthenticatedOddsRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedScoresRoute: typeof AuthenticatedScoresRoute
  AuthenticatedSlateRoute: typeof AuthenticatedSlateRoute
  AuthenticatedStandingsRoute: typeof AuthenticatedStandingsRoute
  AuthenticatedTopPropsRoute: typeof AuthenticatedTopPropsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMatchupsGamePkRoute: typeof AuthenticatedMatchupsGamePkRoute
  AuthenticatedPlayersPlayerIdRoute: typeof AuthenticatedPlayersPlayerIdRoute
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedBetsRoute: AuthenticatedBetsRoute,
  AuthenticatedCalibrationRoute: AuthenticatedCalibrationRoute,
  AuthenticatedCalibrationLabRoute: AuthenticatedCalibrationLabRoute,
  AuthenticatedDiamondConsensusRoute: AuthenticatedDiamondConsensusRoute,
  AuthenticatedDiamondScoresRoute: AuthenticatedDiamondScoresRoute,
  AuthenticatedLeaderboardsRoute: AuthenticatedLeaderboardsRoute,
  AuthenticatedLineupStatusRoute: AuthenticatedLineupStatusRoute,
  AuthenticatedOddsRoute: AuthenticatedOddsRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedScoresRoute: AuthenticatedScoresRoute,
  AuthenticatedSlateRoute: AuthenticatedSlateRoute,
  AuthenticatedStandingsRoute: AuthenticatedStandingsRoute,
  AuthenticatedTopPropsRoute: AuthenticatedTopPropsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMatchupsGamePkRoute: AuthenticatedMatchupsGamePkRoute,
  AuthenticatedPlayersPlayerIdRoute: AuthenticatedPlayersPlayerIdRoute,
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksBeforeUserCreatedRoute: ApiPublicHooksBeforeUserCreatedRoute,
  ApiPublicHooksRefreshLineupsRoute: ApiPublicHooksRefreshLineupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
