// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import type { CustomFetch } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
//
// Some serverFn POST code paths in this version of @tanstack/start-client-core
// drop middleware-returned `headers` before the fetch is built (GET requests
// keep them). To make this robust for both GET and POST we ALSO install a
// custom fetch that re-sets the Authorization header on the actual request.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    if (!token) {
      return next()
    }

    const authedFetch: CustomFetch = async (input, init) => {
      const headers = new Headers(init?.headers ?? undefined)
      headers.set('Authorization', `Bearer ${token}`)
      return fetch(input as RequestInfo, { ...(init ?? {}), headers })
    }

    return next({
      headers: { Authorization: `Bearer ${token}` },
      fetch: authedFetch,
    })
  },
)
